participants:
  - el_type: geth
    el_image: eth2030:local
    cl_type: lighthouse
    cl_image: sigp/lighthouse:latest
    count: 2

network_params:
  network: kurtosis
  seconds_per_slot: 12
  genesis_delay: 10

additional_services:
  - dora
  - spamoor
  - rakoon
  - assertoor

assertoor_params:
  run_stability_check: true

spamoor_params:
  spammers:
    - scenario: eoatx
      name: "EOA Spam"
      config:
        throughput: 50
        max_pending: 100
        max_wallets: 50

rakoon_params:
  tx_type: eip7702
  workers: 10
  fuzzing: true
